### ISSUE TITLE
[Feature Request]: Make non-interactive

### ISSUE THREAD

**Issue by th-alanreed** [darkterminal/turso-php-installer#2]
### Description

Can this be made non-interactive so I can install automatically as part of build script?

### Describe the solution you'd like

`turso-php-installer install -y`

or 

`turso-php-installer install --version=8.3`

or 

`sudo apt install php8.3-turso` (This would be ideal)

### Describe alternatives you've considered

`sudo yes | turso-php-installer install`

**Comment by darkterminal** [comment]
Hi @aarreedd, referring from [turso-docs#224](https://github.com/tursodatabase/turso-docs/issues/224#issuecomment-2272688350) I want to know, did you use something like Herd or something in your environment?

Your request for this feature is really great. Thank you for your suggestion, FYI I am not planing this installer using `apt` at all this the `libsql_php` is not related with any PHP PDO from PHP Internal, cz the extension is built using Rust and not extending any PHP Internal.

I will add support for this request in the future. Thank you!

**Comment by th-alanreed** [comment]
I am using a fresh server created by Laravel Forge

**Comment by th-alanreed** [comment]
Here is another mistake in the install documentation:

After installing successfully, the output of `$ php -m | grep libsql` is `libsql_php` not `liblibsql_php`.

Also, it is strange that the install script is in your personal GitHub rather than Turso's official GitHub

**Comment by darkterminal** [comment]
Laravel Forge (troubleshoot): https://github.com/darkterminal/darkterminal/discussions/3

It's not yet updated, since the troubleshoot is reported by another user. But I will add the detail usage in Laravel Forge.

`libsql_php` is the name of the extension and `liblibsql_php` is the filename.

> it is strange that the install script is in your personal GitHub rather than Turso's official GitHub

Yes it is, cz the PHP Extension of libSQL is not officially build by Turso Team, it's build by me as a community contributor.

**Comment by th-alanreed** [comment]
I assumed you were employed by Turso!

**Comment by darkterminal** [comment]
I am not employed by Turso but Turso sponsored me :smiley: you can also sponsoring me at GitHub :rofl: 

Keep this issue open, until I am support this request.

**Comment by th-alanreed** [comment]
I'll leave it open. I closed it accidentally before

**Comment by darkterminal** [comment]
I've been add your feature request, you can look at [the commit histories](https://github.com/darkterminal/turso-php-installer/commits/main/?since=2024-08-08&until=2024-08-08)
